                                          --Joins
create table student(student_id int primary key,name varchar(40),dept_id int ,foreign key(dept_id) references department(dept_id))
create table department(dept_id int primary key,dept_name varchar(30));
INSERT INTO department (dept_id, dept_name) VALUES
(1, 'Computer Science'),
(2, 'Electronics and Communication'),
(3, 'Mechanical Engineering'),
(4, 'Civil Engineering'),
(5, 'Information Technology');
select * from department;
INSERT INTO student (student_id, name, dept_id) VALUES
(1, 'Arun Kumar', 1),
(2, 'Divya Sri', 2),
(3, 'Praveen Raj', 3),
(4, 'Kavya Lakshmi', 1),
(5, 'Suresh Babu', 4),
(6, 'Meena Priya', 5),
(7, 'Vignesh Waran', 2),
(8, 'Anitha Devi', 3),
(9, 'Karthik Raja', 1),
(10, 'Priya Dharshini', 4),
(11, 'Naveen Kumar', 5),
(12, 'Sowmya Ravi', 2),
(13, 'Sathish Kumar', 3),
(14, 'Deepika Rani', 1),
(15, 'Ramesh Chandran', 4),
(16, 'Nithya Shree', 5),
(17, 'Gokul Raj', 2),
(18, 'Aishwarya S', 3),
(19, 'Bala Murugan', 1),
(20, 'Swetha Menon', 4),
(21, 'Dinesh Kannan', 5),
(22, 'Revathi Suresh', 2),
(23, 'Manoj Kumar', 3),
(24, 'Lavanya Devi', 1),
(25, 'Senthil Kumar', 4),
(26, 'Pooja Iyer', 5),
(27, 'Ashok Prabhu', 2),
(28, 'Divya Bharathi', 3),
(29, 'Rajesh Kanna', 1),
(30, 'Sneha Priya', 4),
(31, 'Vijay Anand', 5),
(32, 'Keerthana R', 2),
(33, 'Muthu Kumar', 3),
(34, 'Harini Sundar', 1),
(35, 'Selvam Raj', 4),
(36, 'Nandhini K', 5),
(37, 'Sudhakar M', 2),
(38, 'Yamuna Devi', 3),
(39, 'Prakash Raj', 1),
(40, 'Gayathri S', 4);
insert into student val