/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminMoviesRouteImport } from './routes/admin/movies'
import { Route as AdminShowsRouteImport } from './routes/admin/shows'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMoviesRoute = AdminMoviesRouteImport.update({
  id: '/admin/movies',
  path: '/admin/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShowsRoute = AdminShowsRouteImport.update({
  id: '/admin/shows',
  path: '/admin/shows',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/shows': typeof AdminShowsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/shows': typeof AdminShowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/shows': typeof AdminShowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/admin/movies' | '/admin/shows'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/admin/movies' | '/admin/shows'
  id: '__root__' | '/login' | '/register' | '/admin/movies' | '/admin/shows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminMoviesRoute: typeof AdminMoviesRoute
  AdminShowsRoute: typeof AdminShowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/movies': {
      id: '/admin/movies'
      path: '/admin/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AdminMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shows': {
      id: '/admin/shows'
      path: '/admin/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AdminShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminMoviesRoute: AdminMoviesRoute,
  AdminShowsRoute: AdminShowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
